name: example
description: Demonstrates how to use the fl_baidu_mob_stat plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  fl_baidu_mob_stat:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
