name: fl_baidu_mob_stat
description: baidu mobstat plugin for flutter, only Android and IOS are supported
version: 1.3.1+1
repository: https://github.com/Wayaer/fl_baidu_mob_stat.git

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: fl.baidu.mob.stat
        pluginClass: BaiduMobStatPlugin
      ios:
        pluginClass: BaiduMobStatPlugin
